<a href="https://colab.research.google.com/github/mvmorr/CE888/blob/master/lab5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import itertools

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import accuracy_score as acc
from sklearn.metrics import make_scorer, confusion_matrix
from sklearn.dummy import DummyRegressor, DummyClassifier
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv",header=None)
df.head()

0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:

df = df.drop(df.columns[0],axis=1)
arr = df.values
new_arr, idx = replace(df.values, 0.1)


In [5]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2
ratings = new_arr
latent_preferences = np.random.random((ratings.shape[0],n_latent_factors))
latent_features = np.random.random((ratings.shape[1], n_latent_factors))

In [7]:
latent_features

array([[0.55926211, 0.38612939],
       [0.52468851, 0.56231425],
       [0.25275699, 0.89327027],
       [0.58551292, 0.16654205],
       [0.87057143, 0.94875207],
       [0.74865226, 0.41248467],
       [0.23163929, 0.93442526],
       [0.37036166, 0.95263094],
       [0.25846485, 0.87677384],
       [0.57085749, 0.12985598],
       [0.23826325, 0.23841608],
       [0.86955577, 0.57986326],
       [0.87361063, 0.03711057],
       [0.76109208, 0.03058966],
       [0.38372967, 0.07968203],
       [0.31177941, 0.75254641],
       [0.88858918, 0.58649317],
       [0.15966534, 0.9239489 ],
       [0.47635668, 0.34012356],
       [0.73399305, 0.70816189],
       [0.00439988, 0.80867228],
       [0.19354332, 0.16244474],
       [0.33154348, 0.77620658],
       [0.28530999, 0.2062624 ],
       [0.29285377, 0.15202009],
       [0.10907995, 0.45522173],
       [0.01598056, 0.68801976],
       [0.67561127, 0.02835802],
       [0.89806783, 0.06214197],
       [0.74131206, 0.89813356],
       [0.

In [8]:
latent_preferences

array([[0.29791772, 0.72142976],
       [0.66616916, 0.24397559],
       [0.23820616, 0.73626377],
       ...,
       [0.15765339, 0.22511866],
       [0.95387201, 0.2181586 ],
       [0.46283959, 0.14008091]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_preferences[user_id]
    item_preference = latent_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_preferences[user_id][:]
    latent_preferences[user_id] -= alpha * err * latent_features[item_id]
    latent_features[item_id] -= alpha * err * user_pref_values
    return err

def sgd(iterations=25):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_preferences.shape[0]):
            for item_id in range(latent_features.shape[0]):
                rating = ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [10]:
sgd()

26.285173254083638
25.302865352506966
25.01120233057793
24.792820670573427
24.581657326703482
24.368936323893088
24.153853724697843
23.937216543554538
23.72027510913509
23.504409036709465
23.29099998144739
23.081356689162924
22.876659801433817
22.677917806889038
22.485931557020745
22.3012659240596
22.124226944112856
21.95484226454387
21.792842318069763
21.63763958847126
21.488303797808424
21.34353208728177
21.201615680044103
21.06040867698749
20.917311227643445


In [11]:
predictions = latent_preferences.dot(latent_features.T)
predictions

array([[0.99247476, 0.9301195 , 0.88063911, ..., 1.23627784, 0.80491885,
        1.41956314],
       [1.20560455, 1.06338225, 0.98327958, ..., 1.3819475 , 0.85068244,
        1.77741489],
       [3.90108204, 3.66655127, 3.47523915, ..., 4.87843445, 3.18406456,
        5.57139616],
       ...,
       [0.25994209, 0.24355878, 0.23058369, ..., 0.32370421, 0.21072001,
        0.37184329],
       [1.00202532, 0.80019036, 0.70845789, ..., 0.99786082, 0.54715535,
        1.54396235],
       [2.26383364, 2.04145543, 1.9044823 , ..., 2.67549486, 1.6827964 ,
        3.30192779]])

In [0]:
values = [zip(ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [0]:
comparison_data

-7.82  ...                         99.25
0       (99.0, 1.4136581523041103)  ...    (1.07, 2.0942129851614593)
1        (99.0, 3.547008068469113)  ...      (99.0, 4.94776632770088)
2       (99.0, 1.1930196833391815)  ...     (99.0, 2.129300105390536)
3        (8.5, 2.5565624283891744)  ...    (99.0, 3.6319112055714813)
4      (-6.17, -2.117786234707847)  ...  (-3.45, -2.7736704457586496)
...                            ...  ...                           ...
24977    (0.44, 2.999153183501996)  ...     (7.43, 4.375123080003649)
24978   (9.13, 1.2401435329027564)  ...    (8.45, 1.3159579940691286)
24979   (99.0, 0.9137410697675387)  ...    (99.0, 1.2203149177420831)
24980   (99.0, 0.4244479480108901)  ...    (99.0, 1.0577987959789017)
24981    (2.43, 2.953924111357296)  ...     (99.0, 3.961591870005143)

[24982 rows x 100 columns]

In [12]:
x, y = idx
len(x)

181045

In [13]:
error = 0
for n in range(len(idx[0])):
  error+=(df.values[x[n]][y[n]]- predictions[x[n]][y[n]])**2
  if n % 100 == 0:
    print(error)


74.87694461117839
2402.5369975113667
4469.187305952994
6760.100134608052
8758.147469711459
10605.444540371765
12848.006264272715
14637.637207245287
16721.73229393905
18917.239285782623
21356.831917763207
23573.740917716623
25895.490085144822
28131.237739722423
30130.266409533186
32269.898656380534
33964.52941671693
36447.20491722332
38346.90953256694
40712.165806859615
42398.282697172486
44104.46435165021
46157.63532041777
47967.15174373899
49983.906107344796
51971.07564460409
54445.52047996879
56558.37344031321
58582.11856108815
61146.13653299954
63436.46239292668
65656.40410137773
67539.9877862958
69880.77072300532
71965.06158678365
73812.6684132345
76024.94253923233
78322.40789509538
80498.43102201023
82639.93670442574
84837.51160376854
86905.58239943872
89127.23124133407
91697.92261369817
94195.98185879008
96409.99962373731
98521.91615882868
100946.10020531803
103330.17543448263
105334.88632167372
106895.9160685651
108961.94235965222
111465.95848358108
114007.85734644577
116538.039

In [14]:
error/len(x)

21.207876631119493